// ─── JOB LISTINGS ────────────────────────────────────────────────
export const mockJobs = [
  {
    id: '1',
    title: 'Senior Product Designer',
    company: 'Stripe',
    companyLogo: null,
    location: 'Remote (Global)',
    type: 'Full-time',
    salary: { min: 120000, max: 160000, currency: 'USD' },
    matchScore: 94,
    industry: 'Fintech',
    level: 'Senior',
    posted: '2 days ago',
    description: 'Lead design initiatives for Stripe\'s developer-facing products. Work closely with engineers and PMs to ship world-class interfaces.',
    requirements: ['5+ years product design', 'Figma expert', 'Design systems experience', 'B2B SaaS background'],
    benefits: ['Equity', 'Health insurance', 'Remote-first', '$2k learning budget'],
    saved: true,
    status: null,
  },
  {
    id: '2',
    title: 'Frontend Engineer (React)',
    company: 'Linear',
    companyLogo: null,
    location: 'San Francisco / Remote',
    type: 'Full-time',
    salary: { min: 140000, max: 180000, currency: 'USD' },
    matchScore: 88,
    industry: 'Productivity',
    level: 'Mid-Senior',
    posted: '1 day ago',
    description: 'Build the next generation of project management tooling. You\'ll be working on performance-critical UI with a small, talented team.',
    requirements: ['4+ years React', 'TypeScript', 'Performance optimization', 'CSS mastery'],
    benefits: ['Equity', 'Health', 'Remote', '$3k hardware budget'],
    saved: false,
    status: 'applied',
  },
  {
    id: '3',
    title: 'UX Researcher',
    company: 'Notion',
    companyLogo: null,
    location: 'New York / Hybrid',
    type: 'Full-time',
    salary: { min: 100000, max: 135000, currency: 'USD' },
    matchScore: 79,
    industry: 'Productivity',
    level: 'Mid',
    posted: '4 days ago',
    description: 'Own the research function for Notion\'s collaboration features. Run studies, synthesize insights, and influence roadmap.',
    requirements: ['3+ years UX research', 'Qualitative & quant methods', 'Startup experience'],
    benefits: ['Equity', 'Health', 'Hybrid', 'Unlimited PTO'],
    saved: true,
    status: null,
  },
  {
    id: '4',
    title: 'Head of Product',
    company: 'Loom',
    companyLogo: null,
    location: 'Remote',
    type: 'Full-time',
    salary: { min: 180000, max: 240000, currency: 'USD' },
    matchScore: 65,
    industry: 'Video / Comms',
    level: 'Leadership',
    posted: '1 week ago',
    description: 'Define and drive product strategy for Loom\'s enterprise segment. Manage a growing team of PMs.',
    requirements: ['8+ years product', '3+ years leadership', 'Enterprise SaaS', 'GTM experience'],
    benefits: ['Equity', 'Health', 'Remote', 'Parental leave'],
    saved: false,
    status: null,
  },
  {
    id: '5',
    title: 'Growth Engineer',
    company: 'Vercel',
    companyLogo: null,
    location: 'Remote',
    type: 'Full-time',
    salary: { min: 130000, max: 165000, currency: 'USD' },
    matchScore: 82,
    industry: 'Dev Tools',
    level: 'Mid-Senior',
    posted: '3 days ago',
    description: 'Build experiments and growth loops that drive developer adoption of Vercel\'s platform.',
    requirements: ['Full-stack (Node/React)', 'Analytics/attribution', 'A/B testing', 'SQL'],
    benefits: ['Equity', 'Health', 'Remote', 'Conference budget'],
    saved: false,
    status: null,
  },
  {
    id: '6',
    title: 'Engineering Manager',
    company: 'Figma',
    companyLogo: null,
    location: 'San Francisco',
    type: 'Full-time',
    salary: { min: 200000, max: 260000, currency: 'USD' },
    matchScore: 71,
    industry: 'Design Tools',
    level: 'Leadership',
    posted: '5 days ago',
    description: 'Lead a team of 6 engineers building Figma\'s real-time collaboration engine.',
    requirements: ['5+ years engineering', '2+ years management', 'Distributed systems', 'Mentorship'],
    benefits: ['Equity', 'Health', 'On-site SF', 'Paid parental leave'],
    saved: false,
    status: 'shortlisted',
  },
]

// ─── CANDIDATE MATCHES (Employer View) ────────────────────────────
export const mockCandidates = [
  {
    id: 'c1',
    name: 'Priya Sharma',
    role: 'Product Designer',
    experience: '6 years',
    skills: ['Figma', 'Design Systems', 'User Research', 'Prototyping'],
    location: 'London, UK',
    salary: { min: 90000, max: 120000 },
    matchScore: 96,
    availability: 'Available now',
    stage: 'shortlisted',
    appliedTo: 'Senior Product Designer',
    education: 'RCA, MA Design',
  },
  {
    id: 'c2',
    name: 'David Osei',
    role: 'Senior Frontend Engineer',
    experience: '8 years',
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL'],
    location: 'Berlin, Germany',
    salary: { min: 100000, max: 140000 },
    matchScore: 91,
    availability: '2 weeks notice',
    stage: 'interviewed',
    appliedTo: 'Frontend Engineer (React)',
    education: 'TU Berlin, CS',
  },
  {
    id: 'c3',
    name: 'Sofia Martínez',
    role: 'UX Researcher',
    experience: '4 years',
    skills: ['Qualitative Research', 'Usability Testing', 'SQL', 'Figma'],
    location: 'Barcelona, Spain',
    salary: { min: 70000, max: 90000 },
    matchScore: 84,
    availability: '1 month notice',
    stage: 'shortlisted',
    appliedTo: 'UX Researcher',
    education: 'Universitat Pompeu Fabra, Psychology',
  },
  {
    id: 'c4',
    name: 'James Kimani',
    role: 'Full Stack Developer',
    experience: '5 years',
    skills: ['Python', 'React', 'AWS', 'PostgreSQL', 'Docker'],
    location: 'Nairobi, Kenya (Remote)',
    salary: { min: 60000, max: 85000 },
    matchScore: 77,
    availability: 'Available now',
    stage: 'applied',
    appliedTo: 'Growth Engineer',
    education: 'University of Nairobi, Engineering',
  },
]

// ─── JOB LISTINGS (Employer-created) ──────────────────────────────
export const mockEmployerJobs = [
  {
    id: 'ej1',
    title: 'Senior Product Designer',
    status: 'active',
    applicants: 23,
    matched: 8,
    shortlisted: 3,
    posted: '2024-12-01',
    salary: { min: 120000, max: 160000 },
    location: 'Remote',
  },
  {
    id: 'ej2',
    title: 'Frontend Engineer (React)',
    status: 'active',
    applicants: 41,
    matched: 12,
    shortlisted: 5,
    posted: '2024-11-28',
    salary: { min: 140000, max: 180000 },
    location: 'SF / Remote',
  },
  {
    id: 'ej3',
    title: 'Head of Growth',
    status: 'paused',
    applicants: 16,
    matched: 4,
    shortlisted: 1,
    posted: '2024-11-15',
    salary: { min: 160000, max: 200000 },
    location: 'Remote',
  },
  {
    id: 'ej4',
    title: 'Data Analyst',
    status: 'closed',
    applicants: 58,
    matched: 19,
    shortlisted: 6,
    posted: '2024-10-20',
    salary: { min: 85000, max: 110000 },
    location: 'New York',
  },
]

// ─── APPLICATIONS ──────────────────────────────────────────────────
export const mockApplications = [
  {
    id: 'a1',
    job: mockJobs[1],
    appliedDate: '2024-12-03',
    stage: 'interviewed',
    lastUpdate: '1 day ago',
    nextStep: 'Technical interview on Dec 12',
  },
  {
    id: 'a2',
    job: mockJobs[5],
    appliedDate: '2024-12-01',
    stage: 'shortlisted',
    lastUpdate: '3 days ago',
    nextStep: 'Awaiting recruiter response',
  },
]

// ─── ADMIN USERS ──────────────────────────────────────────────────
export const mockAdminStats = {
  totalUsers: 12847,
  activeJobSeekers: 9230,
  employers: 1204,
  jobsPosted: 3841,
  matchesMade: 28403,
  avgTimeToHire: 14,
  platformHealth: 99.7,
  todaySignups: 84,
}

export const mockRecentUsers = [
  { id: 'u1', name: 'TechCorp Ltd', type: 'employer', email: 'hr@techcorp.com', status: 'pending', joined: '2h ago' },
  { id: 'u2', name: 'Amara Diallo', type: 'seeker', email: 'amara@email.com', status: 'active', joined: '3h ago' },
  { id: 'u3', name: 'BuildFast Inc', type: 'employer', email: 'jobs@buildfast.io', status: 'verified', joined: '5h ago' },
  { id: 'u4', name: 'Luca Romano', type: 'seeker', email: 'luca.romano@mail.it', status: 'active', joined: '6h ago' },
  { id: 'u5', name: 'Zara Patel', type: 'seeker', email: 'zara.p@outlook.com', status: 'active', joined: '8h ago' },
]

// ─── MESSAGES ──────────────────────────────────────────────────────
export const mockConversations = [
  {
    id: 'm1',
    with: 'Sarah Chen – Talent @ Linear',
    avatar: null,
    lastMessage: 'We\'d love to move you to the next round!',
    time: '10:32 AM',
    unread: 2,
    messages: [
      { from: 'them', text: 'Hi! Thanks for applying to the Frontend Engineer role.', time: '9:00 AM' },
      { from: 'me', text: 'Thank you for reaching out! I\'m very excited about the opportunity.', time: '9:15 AM' },
      { from: 'them', text: 'We\'d love to move you to the next round!', time: '10:32 AM' },
    ],
  },
  {
    id: 'm2',
    with: 'Mike Torres – Figma Recruiter',
    avatar: null,
    lastMessage: 'Let me know your availability for a call.',
    time: 'Yesterday',
    unread: 0,
    messages: [
      { from: 'them', text: 'Hey, your profile caught our eye for the EM role.', time: 'Yesterday' },
      { from: 'them', text: 'Let me know your availability for a call.', time: 'Yesterday' },
    ],
  },
]

// ─── NOTIFICATIONS ─────────────────────────────────────────────────
export const mockNotifications = [
  { id: 'n1', type: 'match', text: '3 new job matches based on your profile', time: '2 mins ago', read: false },
  { id: 'n2', type: 'message', text: 'Sarah Chen from Linear sent you a message', time: '1h ago', read: false },
  { id: 'n3', type: 'update', text: 'Your application to Figma moved to Shortlisted', time: '3h ago', read: true },
  { id: 'n4', type: 'interview', text: 'Interview scheduled with Linear on Dec 12', time: '1 day ago', read: true },
]

// ─── ATS INTEGRATIONS ─────────────────────────────────────────────
export const atsProviders = [
  { id: 'greenhouse', name: 'Greenhouse', connected: true, jobsSynced: 12 },
  { id: 'lever', name: 'Lever', connected: false, jobsSynced: 0 },
  { id: 'workable', name: 'Workable', connected: false, jobsSynced: 0 },
  { id: 'bamboohr', name: 'BambooHR', connected: false, jobsSynced: 0 },
  { id: 'ashby', name: 'Ashby', connected: false, jobsSynced: 0 },
  { id: 'teamtailor', name: 'Teamtailor', connected: false, jobsSynced: 0 },
]
